FROM golang:alpine
MAINTAINER MP

RUN apk update && apk add git ffmpeg ca-certificates && update-ca-certificates

RUN CGO_ENABLED=0 go get github.com/Gookuruto/MusicBotGo

RUN mkdir /bot

WORKDIR /bot

CMD ["MusicBot", "-f", "bot.toml"]